# This is a basic workflow to help you get started with Actions

name: Build_x86_64_def

on: 

  workflow_dispatch:

  #push:
  #  branches: 
  #    - main
  #  paths: 
  #    - logs/x86_64.md

  # schedule:
  #   - cron: 0 8 * * 1
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Cache
      uses: klever1988/cachewrtbuild@main
      with:
        ccache: 'true'
        prefix: ./openwrt
        
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        
    - name: Import external feeds - openclash
      working-directory: ./openwrt
      run: |
        git clone https://github.com/vernesong/OpenClash.git package/openclash
    
    - name: Import external feeds - luci-app-adguardhome
      working-directory: ./openwrt
      run: |
        git clone https://github.com/rufengsuixing/luci-app-adguardhome.git package/luci-app-adguardhome
  
    - name: Import external feeds - JerryKuKu Argon
      working-directory: ./openwrt
      run: |
        git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/lean/luci-theme-argon-18.06

    - name: Import external feeds - JerryKuKu Argon Config
      working-directory: ./openwrt
      run: |
        git clone https://github.com/jerrykuku/luci-app-argon-config.git package/lean/luci-theme-argon-config

    - name: Configuration Customization - Build_x86_64_def
      env:
        CONFIG_FILE: 'x86_64_def.config'
        BANNER_FILE: 'banner'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        [ -e $BANNER_FILE ] && mv $BANNER_FILE openwrt/package/base-files/files/etc/banner
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt
        echo -e 'CONFIG_DEVEL=y\nCONFIG_CCACHE=y' >> .config && make defconfig
        
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        
    - name: Organize Firmware
      if: success()
      run: |
        cd ./openwrt/bin/targets/*/*
        rm -rf packages

    #- name: Upload Packages Directory
    #  uses: actions/upload-artifact@master
    #  if: success()
    #  with:
    #    name: OpenWrt-x86_64_def-Packages
    #    path: openwrt/bin/packages

    - name: Upload Firmware Directory
      uses: actions/upload-artifact@master
      if: success()
      with:
        name: OpenWrt-x86_64_def
        path: openwrt/bin/targets/x86/64

    #- name : Upload artifact
    #  uses: actions/upload-artifact@master
    #  with:
    #    name: OpenWrt
    #    path: openwrt/bin